// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AutomatedDeployment.Api
{
    public partial class Application
    {
        public Application()
        {
            Configurations = new HashSet<Configuration>();
        }

        [Key]
        public int AppID { get; set; }
        [Required]
        [StringLength(50)]
        public string AppName { get; set; }

        [InverseProperty(nameof(Configuration.App))]
        public virtual ICollection<Configuration> Configurations { get; set; }
    }
}