// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AutomatedDeployment.Api
{
    public partial class Hub
    {
        public Hub()
        {
            Configurations = new HashSet<Configuration>();
        }

        [Key]
        public int HubID { get; set; }
        [Required]
        [StringLength(50)]
        public string HubName { get; set; }

        [InverseProperty(nameof(Configuration.Hub))]
        public virtual ICollection<Configuration> Configurations { get; set; }
    }
}